services:

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: minor2-keycloak
    command: start-dev
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN_USERNAME}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    ports:
      - "8080:8080"

  api:
    build:
      context: ./application
    container_name: minor2-api
    ports:
      - "8000:8000"
    depends_on:
      - keycloak